#! /usr/bin/python

import sys, re, os, string

try:
	import pwd
	username = pwd.getpwuid(os.getuid())[0]
except ImportError:
	username = os.getenv('USERNAME')

commit = sys.stdin.read()

print 'arguments = ', sys.argv

islog = 0
for line in string.split(commit, '\n'):
	if re.match('Bug:|Feature:|New:', line):
		islog = 1
		print username

	if re.match('^\s*$', line) is not None:
		islog = 0

	if islog:
		print '\t\t',line
