<h3>Contact the vim-latex-devel team</h3>

<p>
<a
href="mailto://vim-latex-devel[AT]lists.sourceforge.net">vim-latex-devel[AT]lists.sourceforge.net</a>
is a list meant for discussing bugs/feature requests and other things
pertaining to latex-suite. It is <em>not</em> meant to be a developers only
list as the name might imply. You can only e-mail vim-latex-devel directly if you are subscribed to it.
If you wish to subscribe, go to the <a
href="https://lists.sourceforge.net/lists/listinfo/vim-latex-devel">listinfo page</a>.
</p>
<h3>Useful bug reports include a minimal example</h3>
<p>
Please include always files with minimal content that allow to reproduce a bug
you want to report. This often helps to directly find the cause of the bug and
makes it easier for developers to investigate the issue. The features of
vim-latex and latex are way to much, that you can expect the developers to be
familiar with each of it, and every time spent on creating a similiar document
to the one you have, to reproduce the problem, is time wasted on fixing the bug
instead.

You can find more information about minimum examples on the <a
href="http://www.tex.ac.uk/cgi-bin/texfaq2html?label=minxampl">UK List of TeX
Frequently Asked Questions</a> and the <a
href="http://www.minimalbeispiel.de/mini-en.html">minimal working example howto</a>.
</p>
<h3>Check the latest version first</h3>
<p>
Also try to reproduce bugs with the latest version of
vim-latex in the source code management system, before reporting them.
</p>
