<h3>Contact the vim-latex-devel team</h3>

<a
href="mailto://vim-latex-devel[AT]lists.sourceforge.net">vim-latex-devel[AT]lists.sourceforge.net</a>
is a list meant for discussing bugs/feature request and other things
pertaining to latex-suite. It is <em>not</em> meant to be a developers only
list as the name might imply. It is a <em>closed</em> list. This means that
you can only e-mail vim-latex-devel directly if you are subscribed to it.
If you wish to subscribe, go to <a
href="https://lists.sourceforge.net/lists/listinfo/vim-latex-devel">this
page.</a> vim-latex-devel is moderately active list which gets about 3-4
mails per day on average. Otherwise, just use the form below to have an
e-mail sent on your behalf to the list.

<p></p>

<a name="form"></a>
<form action="index.php?subject=contactsubmit&title=Submit%20Form" method="POST" target="_top">

<b>Your Name:</b><br>
<input type="text" name="name" size="66" maxlength="80"><p>
<p>
<b>Your E-mail Address:</b><font size="-4" color="red">[*]</font><br>
<input type="text" name="epost" size="66" maxlength="80"><p>
<p>
<b>Subject:</b><br>
<input type="text" name="subject" size="66" maxlength="80">
<P>
<b>Message:</b> <font size="-4" color="red">[*]</font><br>
<textarea name="message" rows="7" cols="50"></textarea>
<p>
<input name="Submit" value="Submit" type="submit"> 
<input name="Reset" value="Clear Form" type="reset">
<p>
<font size="-4" color="red">[*]</font> Required fields.
</form>
