<h3>Contact the vim-latex-devel team</h3>

<p>
<a
href="mailto://vim-latex-devel[AT]lists.sourceforge.net">vim-latex-devel[AT]lists.sourceforge.net</a>
is a list meant for discussing bugs/feature requests and other things
pertaining to latex-suite. It is <em>not</em> meant to be a developers only
list as the name might imply. You can only e-mail vim-latex-devel directly if you are subscribed to it.
If you wish to subscribe, go to the <a
href="https://lists.sourceforge.net/lists/listinfo/vim-latex-devel">listinfo page</a>.
</p>
