<ul>
<li>
<a href="download/latexSuite.zip" class="list">latexSuite.zip</a>&nbsp;
latest stable version of latexSuite:
(<? echo filesize("download/latexSuite.zip")." b; ";
    echo date("F j, Y", filemtime("download/latexSuite.zip")).")"; ?>
</li>
<li>
<a href="http://cvs.sourceforge.net/cvstarballs/vim-latex-cvsroot.tar.gz" class="list">CVS snapshot</a>
</li>
<li>
User documentation:
</li>
	<ul>
		<li>
		<a href="download/latex-suite.html" class="list">In html format</a>
		</li>
		<li>
		<a href="download/latex-suite.txt" class="list">In vim help .txt format</a>
		</li>
	</ul>
<li>
LaTeX TeX-info documentation:
</li>
	<ul>
		<li>
		<a href="download/latexhelp.html" class="list">In html format</a>
		</li>
		<li>
		<a href="download/latexhelp.txt" class="list">In vim help .txt format</a>
		</li>
	</ul>
</ul>

<!-- 
vim:ft=php 
-->
