Vim-Latex aims at providing a comprehensive set of tools so you can do all
you latekng from within vim. Take a look at the <a
href="index.php?subject=screenshots">screenshots</a> to see a typical
working session with latex-suite. Here's a brief tour of the various
features:
<ul>
<li><a href="download/latex-suite.html#latex-compiling">Compiling</a> You
	can compile the tex file from within vim. The list of errors is shown
	in a quickfix window so you can directly go to the location of an
	error. The compiler plugin can be dynamically reconfigured to show you
	more or less warnings.<p></p>
</li>
<li><a href="download/latex-suite.html#latex-viewing">Viewing</a> By
	pressing a key from within vim, the .dvi viewer is started up. You can
	also do <a href="download/latex-suite.html#latex-searching">forward and
	inverse searching</a> on your .dvi file from within vim.<p></p>
</li>
<li>special, improved rules of folding for LaTeX environments and sections</li>
<li>easy for configuration set of LaTeX menus with hundreds of items</li>
<li>dictionary with over 600 LaTeX commands</li>
<li>possibilty of adding templates (TeX-Suite &gt; Templates)</li>
<li>possibilty of adding macros (TeX-Suite &gt; Macros)</li>
<li>analyze of preamble and adding menus and special commands for used packages<br>
see <a href="http://vim-latex.sourceforge.net?subject=packages">list of supported packages</a></li>
<li>set of intuitive shortcuts for inserting environments, sections and font formats</li>
<li>LaTeX help file</li>
</ul>
