<ul>
<li>improved compilator</li>
<li>possibility of viewing .dvi file from Vim</li>
<li>special, improved rules of folding for LaTeX environments and sections</li>
<li>easy for configuration set of LaTeX menus with hundreds of items</li>
<li>dictionary with over 600 LaTeX commands</li>
<li>possibilty of adding templates (TeX-Suite->Templates)</li>
<li>possibilty of adding macros (TeX-Suite->Macros)</li>
<li>analyze of preamble and adding menus and special commands for used packages<br>
see <a href="http://vim-latex.sourceforge.net?subject=packages">list of supported packages</a></li>
<li>set of intuitive shortcuts for inserting environments, sections and font formats</li>
<li>LaTeX help file</li>
</ul>
