<html lang="pl">
<head>
	<title>VIM-LaTeX <? echo $pagetitle ?></title>
	<meta http-equiv="content-type" content="text/html; charset=iso-8859-1">
	<meta http-equiv="content-Language" content="en-US">
	<link rel="stylesheet" href="style.css">
</head>
<body>

<table width=95% cellpadding="0" cellspacing="0" border="0" class="head">
	<tr>
		<td class=leftpanel>
			<a href="index.php">
			<img src="vim-latex.gif" alt="VIM The Editor" width="115" height="32" border="0">
			</a><br>
			<a href="index.php?subject=download">Download</a><br>
			<p></p>
			<hr class=navig>
			<div class=navheader>Documentation</div>
			<a href="index.php?subject=manual">User Manual</a><br>
			<a href="download/latexhelp.html">LaTeX Reference</a><br>
			<a href="index.php?subject=faq">FAQ</a><br>
			<a href="index.php?subject=comingsoon">Tutorial</a><br>
			<a href="index.php?subject=features">Features</a><br>
			<a href="index.php?subject=screenshots">Screenshots</a><br>
			<p></p>
			<hr class=navig>
			<div class=navheader>Support</div>
			<a href="index.php?subject=weare">We are ...<br>
			<a href="index.php?subject=comingsoon">Feature Requests</a><br>
			<a href="index.php?subject=comingsoon">Bug Reports</a><br>
			<p></p>
			<a href="index.php?subject=packages">Package files</a><br>
			<a href="index.php?subject=templates">Templates</a><br>
			<p></p>
			<hr class=navig>
			<div class=navheader>Developers</div>
			<a href="http://cvs.sourceforge.net/cgi-bin/viewcvs.cgi/vim-latex/vimfiles">CVS</a><br>
			<a href="index.php?subject=links">Links</a><br>
			<img src="blank.gif" height="150" width="1"><br>
			<p class="doublesmall">
			Site hosted by:<br>
			<a href="http://sourceforge.net">
				<img src="http://sourceforge.net/sflogo.php?group_id=52322&type=1" width="88" height="31" border="0" alt="SourceForge Logo">
			</a><br>
			<img src=vim_created.gif alt="Created with Vim" width="90" height="36">
			</p>

		</td>
		<!-- main table will continue in index.php -->
