<html lang="pl">
<head>
  <title>VIM-latexSuite <? echo $pagetitle ?></title>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1">
  <meta http-equiv="content-Language" content="en-US">
  <link rel="stylesheet" href="style.css">
</head>
<body>

<div id="header">
  <table width="800" cellpadding="0" cellspacing="0" class="head">
    <tr>
      <td width="120">
        <img src="vimtheeditor.gif" alt="VIM The Editor" width="" height="" border="0">
      </td>
      <td width="1px">
      </td>
      <td width="480" class="menu">
        <span class="menu">
        : :&nbsp;<a href="index.php">Home</a>&nbsp;: :&nbsp;
        <a href="index.php?subject=features">Features</a>&nbsp;: :&nbsp;
        <a href="index.php?subject=packages">Package files</a>&nbsp;: :&nbsp;
        <a href="index.php?subject=templates">Templates</a>&nbsp;: :&nbsp;
        <a href="index.php?subject=screenshots">Screenshots</a>&nbsp;: :&nbsp;
        <a href="index.php?subject=links">Links</a>&nbsp;: :&nbsp;
        <a href="index.php?subject=weare">We&nbsp;are...</a>&nbsp;: :
		<a href="http://cvs.sourceforge.net/cgi-bin/viewcvs.cgi/vim-latex/vimfiles">CVS</a>&nbsp;: :&nbsp;
        <a href="index.php?subject=download">Download</a>&nbsp;: :
        </span>
      </td>
      <td width="150" rowspan="2">
      </td>
    </tr>
  </table>
</div>
