<html>
<head>
	<title>VIM-LaTeX <? echo $pagetitle ?></title>
	<meta http-equiv="content-type" content="text/html; charset=iso-8859-1">
	<meta http-equiv="content-Language" content="en-US">
	<link rel="stylesheet" href="style.css">
</head>
<body>
<table width=95% cellpadding="0" cellspacing="0" border="0" class="head">
	<tr>
		<td class=leftpanel>
			<a href="index.php">
			<img src="vim-latex.gif" alt="VIM The Editor" width="115" height="32" border="0">
			</a><br>
			<a href="index.php?subject=download&title=Download">Download</a><br>
			<p></p>
			<hr class=navig>
			<div class=navheader>Documentation</div>
			<a href="index.php?subject=manual&title=Manual#user-manual">User Manual</a><br>
			<a href="index.php?subject=manual&title=LaTeX%20Reference#latex-reference">LaTeX Reference</a><br>
			<a href="index.php?subject=faq&title=FAQ">FAQ</a><br>
			<a href="index.php?subject=manual&title=Tutorial#tutorial">Tutorial</a><br>
			<a href="index.php?subject=features&title=Features">Features</a><br>
			<a href="index.php?subject=screenshots&title=Screenshots">Screenshots</a><br>
			<p></p>
			<hr class=navig>
			<div class=navheader>Support</div>
			<a href="index.php?subject=weare&title=People">We are ...<br>
			<a
			href="index.php?subject=contact&title=Contact">Feature
			Requests <br/>Bug Reports <br/>Mailing List <br/></a><br>
			<p></p>
			<a href="http://vim-latex.svn.sourceforge.net/viewvc/vim-latex/trunk/vimfiles/ftplugin/latex-suite/packages/">Package files</a><br>
			<a href="http://vim-latex.svn.sourceforge.net/viewvc/vim-latex/trunk/vimfiles/ftplugin/latex-suite/templates/">Templates</a><br>
			<p></p>
			<hr class=navig>
			<div class=navheader>Developers</div>
			<a href="http://vim-latex.svn.sourceforge.net/viewvc/vim-latex/">SVN Webinterface</a><br>
			<a href="http://sourceforge.net/svn/?group_id=52322">SVN instructions</a><br>
			<a href="index.php?subject=links&title=Links">Links</a><br>
			<img src="blank.gif" height="150" width="1"><br>
			<p class="doublesmall">
			Site hosted by:<br>
			<a href="http://sourceforge.net">
				<img src="http://sourceforge.net/sflogo.php?group_id=52322&type=1" width="88" height="31" border="0" alt="SourceForge Logo">
			</a><br>
			<img src=vim_created.gif alt="Created with Vim" width="90" height="36">
			</p>

		</td>
		<!-- main table will continue in index.php -->
