<h3>Vim Stuff</h3>
<ul>
	<li> <a href="http://vim.sourceforge.net" class="extlinks">*The* vim
	page</a> -- A virtual treasury of vim scripts and tips. Many of them
	are related to LaTeX editing. </li>
</ul>
<h3>Latex-Suite stuff</h3>
<ul>
	<li><a href="http://sourceforge.net/projects/vim-latex/">Vim-latex
	project on sourceforge</a></li>
	<li><a href="index.php?subject=coding-style">Coding style used in the
	Latex-Suite project</a></li>
	<li><a
	href="index.php?subject=branching&title=Branching%20Cheat%20Sheet">CVS
	Branching HOWTO</a></li>
    <!--
	<li><a
	href="index.php?subject=patch&title=Submitting%20a%20patch">Submitting
	a patch.</a></li>
    -->
</ul>

<!--
vim:ft=php
-->
