<p><a href="http://vim.sf.net">Vim</a> is undoubtedly one of the best
editors ever made. <a href="http://www.latex-project.org/">LaTeX</a> is an
extremely powerful, intelligent typesetter. Vim-LaTeX aims at bringing
together the best of both these worlds.</p> <p>We attempt to provide a
comprehensive set of tools to view, edit and compile LaTeX documents
without needing to ever quit Vim. Together, they provide tools starting
from macros to speed up editing LaTeX documents to compiling tex files to
forward searching .dvi documents.</p> <p>See the <a
href="index.php?subject=features&title=Features">features page</a> for a
brief tour of the various features in LaTeX-suite. All these features can
be tuned extensively using the included <tt>texrc</tt> file. The <a
href="index.php?subject=screenshots&title=Screenshots">screenshots page</a>
shows you how a typical working session with LaTeX-suite might progress.
<p>LaTeX-suite is made for Vim versions 6.0 and above. Installation
instructions are given in the <a
href="index.php?subject=download&title=Download">download page</a>.</p>

<!--
vim:ft=php
-->
