<p><a href="http://vim.sf.net">Vim</a> is undoubtedly one of the best
editors ever made. <a href="http://www.latex-project.org/">LaTeX</a> is an
extremeley powerful, intelligent typesetter. Vim-LaTeX aims at bringing
together the best of both these worlds.</p>
<p>We attempt to provide a comprehensive set of tools to view, edit and
compile LaTeX documents without needing to ever quit Vim. Together, they
provide tools starting from macros to speed up editing LaTeX documents to
compiling tex files to forward searching .dvi documents.</p>
<p>See the <a href="index.php?subject=features">features page</a> for a
brief tour of the various features in LaTeX-suite. All these features can
be tuned extensively using the included <tt>texrc</tt> file. The
<a href="index.php?subject=screenshots">screenshots page</a> shows you how
a typical working session with LaTeX-suite might progress.
<p>LaTeX-suite is made for Vim versions 6.0 and above. Installation
instructions are given in the <a href="index.php?subject=download">download
page</a>.</p>
