<a name="user-manual"></a>
<h2>User Manual</h2>
Documentation for Latex-Suite is available in the following formats:
<ul>
<li>
	<a href="documentation/latex-suite/">Read online</a>.
	These are a series of HTML files each describing a single section of the
	manual. This should be the best for online reading.
	<p></p>
</li>
<li>
	<a href="documentation/latex-suite.html">Print for offline viewing</a>. This is a
	single HTML file for printing.
	<p></p>
</li>
<li>
	<a href="documentation/latex-suite.txt">Native vim-help format</a>. This
	file should be installed in <tt>~/.vim/doc/latex-suite.txt</tt> when you
	install latex-suite.
	<p>
	This file can be viewed by doing <tt>:help latex-suite.txt</tt> from
	within vim after downloading latex-suite and following the installation
	instructions.
	</p>
	<p></p>
</li>
</ul>

<a name="tutorial"></a>
<h2>Beginner's tutorial</h2>
There is a beginner's tutorial for Latex-suite available in the following
formats:
<ul>
<li>
	<a href="documentation/latex-suite-quickstart/">Read online</a>.
	These are a series of HTML files each describing a single section of the
	manual. This should be the best for online viewing.
	<p></p>
</li>
<li>
	<a href="documentation/latex-suite-quickstart.html">Print</a>.
	This is a single HTML file for printing.
	<p></p>
</li>
<li>
	<a href="documentation/latex-suite-quickstart.txt">Native vim-help
	format</a>. This file should be installed in
	<tt>~/.vim/doc/latex-suite-quickstart.txt</tt> when you install latex-suite.
	<p>
	This file can be viewed by doing 
	<tt>:help latex-suite-quickstart.txt</tt> 
	from within vim after downloading latex-suite and following the
	installation instructions.
	</p>
	<p></p>
</li>
</ul>

<a name="latex-reference"></a>
<h2>LaTeX Reference</h2>
Latex-Suite comes ships with edition 1.6 of the LaTeX2e documentation
translated into vim-help format. This file can be downloaded separately from
Latex-Suite <a href="download/latexhelp.txt">here</a>. After downloading
this file to <tt>~/.vim/doc</tt>, you will need to run the <tt>:helptags</tt>
command from within vim to view LaTeX help from within Vim. 
<p>
Click <a href="download/latexhelp.html">here</a> for a quick peek at how this
might look from within vim. (The color-scheme is of course specific to your
preferences).  
</p>
<p>Type <tt>:help helptags</tt> from within Vim for more information</p>.

<a name="vim-latex-ref-card"></a>
<h2>Vim-Latex Reference Card</h2>
Michael Goerz created a <a href="http://users.physik.fu-berlin.de/~mgoerz/blog/refcards/#latexsuite">a incomplete reference card for vim-latex key bindings</a>.

<?php
// vim:ft=php:noet:ts=4
?>
