<a name="user-manual"></a>
<h2>User Manual</h2>
Documentation for Latex-Suite is available in the following formats:
<ul>
<li>
	<a href="documentation/latex-suite.txt">Native vim-help format</a>. This
	file should be installed in <tt>~/.vim/doc/latex-suite.txt</tt> when you
	install latex-suite.
	<p>
	This file can be viewed by doing <tt>:help latex-suite.txt</tt> from
	within vim after downloading latex-suite and following the installation
	instructions.
	</p>
	<p></p>
</li>
<li>
	<a href="documentation/latex-suite.html">A Flat HTML file</a>. This is a
	single HTML file for printing.
	<p></p>
</li>
<li>
	<a href="documentation/latex-suite/">A set of chunked HTML files</a>.
	These are a series of HTML files each describing a single section of the
	manual. This should be the best for online viewing.
	<p></p>
</li>
</ul>

<a name="latex-reference"></a>
<h2>LaTeX Reference</h2>
Latex-Suite comes ships with edition 1.6 of the LaTeX2e documentation
translated into vim-help format. This file can be downloaded seperately from
Latex-Suite <a href="documentation/latexhelp.txt">here</a>. After downloading
this file to <tt>~/.vim/doc</tt>, you will need to run the <tt>:helptags</tt>
command from within vim to view LaTeX help from within Vim. 
<p>
Click <a href="download/latexhelp.html">here</a> for a quick peek at how this
might look from within vim. (The colorscheme is ofcourse specific to your
preferences).  
</p>
<p>Type <tt>:help helptags</tt> from within Vim for more information</p>.

<?php
// vim:ft=php:noet:ts=4
?>
