<h3>Current Maintainers</h3>
<blockquote>
<p><b>Srinath Avadhanula</b> --
author of <a
href="http://vim.sourceforge.net/script.php?script_id=95">winmanager.vim</a>
and few other scripts for VIM.</p>
<p><b>Mikolaj Machowski</b>  -- ``author'' of
LaTeXhelp for VIM (which is bundled with vim-latexSuite).</p>
<p><b>Benji Fisher</b> -- author of <a
href="http://vim.sourceforge.net/script.php?script_id=39">matchit.vim</a>
and maintainer of the standard tex ftplugin for vim.</p>
</blockquote>
To contact the maintainers for bug reports/feature requests/contributions,
go <a href="index.php?subject=contact&title=Contact">here</a>.
<p>
<h3>Contributors</h3>
LaTeX-Suite has been possible because of the contributions of many people. Among
them:</p>
<blockquote>
<b>Lubomir Host</b> -- provided the diacritics and also helped in development.<br>
<b>Alexander Wagner</b> -- valuable suggestions during development.<br>
<b>Luc Hermitte</b> -- his variation of Stephen Riehm's bracketing system is used
                    in latex-suite.<br>
<b>Gergely Kontra</b> -- the clever little JumpFunc() in imaps.vim is due to him.<br>
                    The implementation of the templates also borrows from
                    mu-template.vim by him.<br>
<b>Dimitri Antoniou</b> -- author of ltags and also provided the nice tip about
                    forward / reverse search on DVI documents.<br>
<b>Stephen Riehm</b> -- the extremely helpful bracketing system is from him.<br>
<b>Alan Schmitt</b> -- provided some macros/folding elements.<br>
<b>Hari Krishna Dara</b> -- for ExecMap(), the clever little function which makes
                    typing visual mode mappings so much easier and error-free.<br>
<b>Alan G Isac</b> -- for the comprehensive BibT() function for entering bibtex
                    entries.<br>
<b>Gontran Baerts</b> -- for libList.vim<br>
<b>Peter Heslin</b> -- useful discussion and also quite a few bug fixes.
	Also the %%fakesection in folding.vim.

</blockquote>
